### PR TITLE
One setup page

### PR DESCRIPTION
**Pull request by ErinBecker**
Whew! This ended up being more involved than I anticipated.

This PR implements changes to the Ecology workshop overview page in conjunction with [this RFC](https://github.com/carpentries/maintainer-RFCs/issues/3) and [the corresponding PR](https://github.com/carpentries/workshop-template/pull/608). The main changes are: 

- Create a centralized Setup page with all install instructions and data downloads that learners will need for the entire workshop. To start this process, I've copied over install instructions from each lesson setup page and re-formatted them to be consistent with one another. The level of detail described in each setup page was different, so there is some work to do to make this read smoothly, but at least all the information is in one place now! (Note - for OpenRefine, I used @libcce's excellent instructions from the LC lesson as these were more up to date.)

- Updated the index page to share the same overall structure as other DC curricula. 

Note: Since no workshops teach both R and Python, and many don't teach the SQL lesson either, no one learner needs all of the setup information currently shown on this page. @fmichonneau is going to build on this PR to have at least two separate URLs - both will have the core content, and will use some of the jekyll structure to include either the R or Python instructions. Learners will be directed to the correct page based on the value of the `flavor` variable in their workshop website.

### CODE REVIEW

**Comment by ErinBecker** [comment]
After adjusting this PR to add the structure noted above, we will need to take down instructions on the individual lessons' setup pages and point people here.

**Comment by ErinBecker** [comment]
Will also need to give all DC Ecology lesson maintenance teams write privileges to this repo, so they can update install instructions as needed.

**Comment by ErinBecker** [comment]
@maneesha - could you please confirm that all ecology maintainer teams have write access to this repo?

**Comment by maneesha** [comment]
I just added all the ecology teams to this repo.  Please let me know if anything doesn't seem right.

**Pull request merged**
